# Generated by Django 3.2.11 on 2022-01-17 04:04

import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Company Agent',
                'verbose_name_plural': 'Company Agents',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Houmer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_leaving_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Houmer',
                'verbose_name_plural': 'Houmers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'unique_together': {('coordinate', 'address')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='houmers.houmer')),
                ('houmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='houmers.houmer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houmers.property')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HoumerHistoricalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('houmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='houmers.houmer')),
            ],
            options={
                'verbose_name': 'Houmer historical location',
                'verbose_name_plural': 'Houmers historical locations',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
